//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod beatmaps;
pub mod beatmapsets;
pub mod role_assignments;
pub mod roles;
pub mod submission_ratings;
pub mod submission_review_ratings;
pub mod submission_reviews;
pub mod submissions;
pub mod users;
