//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::beatmaps::Entity as Beatmaps;
pub use super::beatmapsets::Entity as Beatmapsets;
pub use super::role_assignments::Entity as RoleAssignments;
pub use super::roles::Entity as Roles;
pub use super::submission_ratings::Entity as SubmissionRatings;
pub use super::submission_review_ratings::Entity as SubmissionReviewRatings;
pub use super::submission_reviews::Entity as SubmissionReviews;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
