//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::beatmaps::Entity as Beatmaps;
pub use super::beatmapsets::Entity as Beatmapsets;
pub use super::ratings::Entity as Ratings;
pub use super::role_assignments::Entity as RoleAssignments;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::submission_reviews::Entity as SubmissionReviews;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
