//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "submissions"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: i32,
    pub submitter_id: i32,
    pub beatmapset_id: i32,
    pub submitted_at: DateTime,
    pub game_mode: i16,
    pub reason: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    SubmitterId,
    BeatmapsetId,
    SubmittedAt,
    GameMode,
    Reason,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        true
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Beatmapsets,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Integer.def(),
            Self::SubmitterId => ColumnType::Integer.def(),
            Self::BeatmapsetId => ColumnType::Integer.def(),
            Self::SubmittedAt => ColumnType::DateTime.def(),
            Self::GameMode => ColumnType::SmallInteger.def(),
            Self::Reason => ColumnType::String(StringLen::None).def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Beatmapsets => Entity::belongs_to(super::beatmapsets::Entity)
                .from(Column::BeatmapsetId)
                .to(super::beatmapsets::Column::Id)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::SubmitterId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::beatmapsets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Beatmapsets.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
