FROM node:18-alpine3.21

WORKDIR /app

RUN apk add --no-cache \
    python3 \
    make \
    g++

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

# TODO: make this port configurable
EXPOSE 4000 

CMD ["yarn", "start"]