FROM rustlang/rust:nightly-alpine3.21 AS builder

COPY --link . /app
WORKDIR /app

RUN apk update && apk upgrade \
    && apk add --no-cache \
    alpine-sdk \
    libpq-dev \
    pkgconfig \
    && apk cache clean

RUN cargo build --release

ENTRYPOINT ["/app/target/release/server"]
