name: Lint and Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rust-check:
    name: Rust Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          profile: minimal
      - name: Install Clippy
        run: rustup component add clippy
      - name: Check
        run: cargo check --all
      - name: Clippy
        run: cargo clippy -- -D clippy::all -A clippy::new_without_default

  website-ts-check:
    name: Website Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/website
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: 'yarn'
      - run: yarn install --immutable
      # TODO: implement linting
      #- run: yarn lint
